///*
//package com.jinninghui.newspiral.common.entity.ddos;
//
//public enum InterfaceEnum {
//    callExecuteBusinessSmartContract("ServiceForSDKImpl","业务写智能合约"),
//    callQueryBusinessSmartContract("ServiceForSDKImpl","业务读合约调用权限"),
//            callQuerySmartContract("ServiceForSDKImpl","系统读合约调用"),
//    queryTransactionByTransClientTxId("ServiceForSDKImpl","根据交易的客户端ID查询交易"),
//            queryTransactionByTransHash("ServiceForSDKImpl","根据交易的全局ID（即hash）查询交易"),
//    queryTransByBlockHashAndTransIndex("ServiceForSDKImpl","根据交易所属区块Hash和交易在区块中的序号查询交易"),
//            getTransactionsByHash("ServiceForSDKImpl","查询某个区块的所有交易"),
//    queryTxHistory("ServiceForSDKImpl","根据世界状态key查询相关的交易历史"),
//            queryBlockByHash("ServiceForSDKImpl","根据区块哈希查询区块（不包含交易列表）"),
//    queryBlockByHeight("ServiceForSDKImpl","根据区块高度查询区块（不包含交易列表）"),
//            queryLatestBlockList("ServiceForSDKImpl","查询某个通道在本节点的最新的区块信息"),
//    queryBlockByTransHash("ServiceForSDKImpl","根据交易哈希查询所属区块（不包含交易列表）"),
//            queryBlockByTransClientTxId("ServiceForSDKImpl","根据交易的客户端ID查询所属区块（不包含交易列表)"),
//    queryBlockByHeightRegion("ServiceForSDKImpl","根据高度范围查询区块列表（不包含交易列表）"),
//            queryWorldState("ServiceForSDKImpl","查询世界状态"),
//    version("ServiceForSDKImpl","节点程序版本号查询"),
//            getPeerCurrentState("ServiceForSDKImpl","查询节点当前状态：状态、服务地址、系统负载信息、加入的通道简要信息"),
//    removeAllChannel("ServiceForSDKImpl","删除所有通道"),
//            removePeerFromChannel("ServiceForSDKImpl","从通道中删除一个节点"),
//    deleteChannel("ServiceForSDKImpl","删除通道"),
//            createChannel("ServiceForSDKImpl","创建通道"),
//    callExecuteSmartContract("ServiceForSDKImpl","系统写合约调用"),
//            stopPeer("ServiceForSDKImpl","停止节点"),
//
//
//    exitMyPeerFromChannel("SystemSmartContract","将本节点退出某个通道"),
//            addBlockVoteMsg("ServiceForPeerImpl","处理通道的BlockVote消息"),
//    addGenericMsg("ServiceForPeerImpl","增加GenericMsg消息"),
//            addNewViewMsg("ServiceForPeerImpl","处理某个通道的NewView消息"),
//    addSDKTranscation("ServiceForPeerImpl","新交易加入交易池"),
//            queryBlockByHash("ServiceForPeerImpl","根据区块Hash查询某个区块"),
//    queryBlockByHeight("ServiceForPeerImpl","根据区块高度查询某个区块"),
//            queryChainState("","参与共识之前获取链状态"),
//    queryChainSummary("","查询某个通道的区块链概要信息"),
//            queryChannel("","返回简单的可以向通道外公布的通道信息"),
//    queryChannelBasicParams("","查询某个节点保存的某个通道基础参数"),
//            queryHistoryBlock("","查询历史块"),
//    queryHistoryQC("","查询历史QC"),
//            queryViewNo("","获取当前节点的view值"),
//    removePeerFromChannel("","从通道里移除节点"),
//            queryPeerOrganizationState("","查询节点组织状态"),
//
//
//    updateChannelBlockMaxSize("","通道参数管理"),
//            addOnePeer("","添加节点至通道"),
//    removeOnePeer("","从通道删除某节点"),
//            updatePeerCertificate("","更新节点证书"),
//    updatePeerCertificateState("","更新节点证书状态"),
//            getRole("","查询角色"),
//    getRoleList("","查询角色列表"),
//            addCustomRole("","添加自定义角色"),
//    updateCustomRole("","修改自定义角色"),
//            getMember("","成员查询"),
//    getMemberList("","成员列表查询"),
//            addMember("","添加成员（组织和业务应用）"),
//    updateMember("","更新成员（组织和业务应用）"),
//            getSmartContract("","智能合约查询"),
//    getSmartContractList("","智能合约列表查询"),
//            updateSmartContractAuthorized("","业务智能合约管理"),
//    updateSmartContractState("","业务智能合约管理"),
//            deploySmartContract("","部署和升级业务智能合约"),
//    deleteMember("","删除成员（组织和业务应用）"),
//            queryWholeBlockByHash("","根据区块Hash查询某个区块完整信息"),
//    queryWholeBlockByHeight("","根据区块高度查询某个区块完整信息"),
//            queryWholeBlockByTransHash("","根据交易Hash查询某个区块完整信息"),
//    queryWholeBlockByTransClientTxId("","根据交易客户端Id查询某个区块完整信息"),
//            deleteCustomRole("","删除自定义角色"),
//    queryConsensesStateOfPeer("","查询节点在某个通道的共识状态"),
//            queryTransOfBlockByBlockHash("","根据区块中的交易序号范围查询某区块的交易列表"),
//    addMySelf2Channel("","节点加入通道"),
//            queryAllChannelOfPeer("","查询节点的所有通道信息"),
//    queryOneChannelOfPeer("","查询节点所属最新通道信息"),
//            changeLoggerLevel("","动态修改日志级别"),
//    queryLoggerLevel("","查询日志级别"),
//            queryInterfaceRecord("","查询接口调用详细记录"),
//    queryInterfaceRecordSummary("","查询接口调用总体情况"),
//            queryShardingConfig("","查询sharding配置接口"),
//    modifySharidngRuleConfig("","修改sharding的分库规则配置接口"),
//            modifyShardingDataSourceConfig("","修改sharding的分库规则配置接口"),
//    addShardingDataSourceConfig("","新增sharding的数据源配置接口"),
//            refreshShardingConfig("","启用sharding配置接口");
//
//    InterfaceEnum(String className,String message){
//        this.className = className;
//        this.message = message;
//    }
//}
//*/
